-- 집합연산자
-- 차집합(MINUS)
-- 상위에 작성한 SELECT 문의 결과에서 하위에 작성한 SELECT 문의 결과를 제외한 결과 출력

-- 사원정보에서 부서가 10 이 아닌 사원정보를 출력
SELECT * FROM EMP -- 상위
MINUS
SELECT * FROM EMP WHERE DEPTNO = 10; -- 하위

-- 사원정보에서 부서가 10, 20 이 아닌 사원정보를 출력
SELECT * FROM EMP -- 상위
MINUS
SELECT * FROM EMP WHERE DEPTNO = 10 -- 하위
MINUS
SELECT * FROM EMP WHERE DEPTNO = 20; -- 하위

-- EMP - EMP2
SELECT EMPNO, ENAME, SAL, SAL*12 AS ANNUAL FROM EMP
MINUS
SELECT *FROM EMP2 WHERE ANNUAL <36000;

-- EMP - EMP3
SELECT * FROM EMP
MINUS
SELECT * FROM EMP3;

-- EMP2 - EMP3
SELECT EMPNO, ENAME FROM EMP2
MINUS
SELECT EMPNO, ENAME FROM EMP3;


SELECT * FROM EMP WHERE ENAME = 'KING'
UNION ALL
SELECT * FROM EMP3 WHERE ENAME = 'KING';




