-- 조인JOIN

SELECT * FROM EMP; -- 컬럼 12개
SELECT * FROM DEPT; -- 컬럼 4개

-- 카티시안 프로덕션, 크로스 조인
SELECT * FROM EMP E, DEPT D ORDER BY E.EMPNO, E.DEPTNO, D.DEPTNO; -- 컬럼 48개

-- 등가조인(EQUAL JOIN) 동등조인, 내부조인, 단순조인
SELECT * FROM EMP E, DEPT D WHERE E.DEPTNO = D.DEPTNO ORDER BY E.EMPNO;

-- [문제]
-- 급여가 3000 미만이면서 수당이 없는 사원
-- 사원정보, 부서정보(부서코드, 부서이름, 부서위치)
SELECT E.EMPNO,	E.ENAME, E.JOB,	E.MGR,	E.HIREDATE,	E.SAL,	E.COMM,	E.DEPTNO AS DEPTNO_E, D.DEPTNO AS DEPTNO_D, D.DNAME, D.LOC
  FROM EMP E, DEPT D 
  WHERE  E.SAL < 3000 AND E.DEPTNO = D.DEPTNO  AND E.COMM =0 OR E.COMM IS NULL ;
  
SELECT E.EMPNO,	E.ENAME, E.JOB,	E.MGR,	E.HIREDATE,	E.SAL,	E.COMM,	E.DEPTNO AS DEPTNO_E, D.DEPTNO AS DEPTNO_D, D.DNAME, D.LOC
  FROM EMP E, DEPT D 
  WHERE  E.SAL < 3000 AND E.DEPTNO = D.DEPTNO  AND (E.COMM =0 OR E.COMM IS NULL) ;