CREATE TABLE HELLO
(
    ID CHAR(5) CONSTRAINT PK_HELLO_ID PRIMARY KEY,
    NAME VARCHAR2(20),
    TEL VARCHAR2 (20),
    AGE NUMBER(3)
);
    
INSERT INTO "MIMMI"."HELLO" (ID, NAME, TEL, AGE) VALUES ('12345', '홍길동', 010-1234-1234,30);

DROP TABLE HELLO;

--[문제] 전화번호부
-- 테이블명: PHONEBOOK
-- 필드목록: ID, NAME, PHONENUMBER, HOMECALLNUMBER, ADDRESS, Zip code, ,EMAIL, GROUPNAME, MEMO
-- GROUPNAME : FAMILY, ACCOUNT, RELATIVE...

-- 테이블명: PHONEGROUP