-- SELECT INTO
-- 窜老青 单捞磐 历厘

SET SERVEROUTPUT ON;

DECLARE
    V_DEPT_ROW DEPT%ROWTYPE;
BEGIN
    SELECT DEPTNO, DNAME, LOC INTO V_DEPT_ROW
        FROM DEPT
        WHERE DEPTNO = 40;
        
        DBMS_OUTPUT.PUT_LINE('DEPTNO : ' ||V_DEPT_ROW.DEPTNO);
        DBMS_OUTPUT.PUT_LINE('DNAME : ' ||V_DEPT_ROW.DEPTNO);
        DBMS_OUTPUT.PUT_LINE('LOC : ' ||V_DEPT_ROW.DEPTNO);
END;
/