--조회

-- 1. EMP 테이블 조회 (테이블 정보)
DESC EMP;


--2. 행단위 조회 : 셀렉션(SELECTION)
-- *을 사용하면 전부 다 출력됨
SELECT * FROM EMP;
SELECT EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO FROM EMP;
SELECT EMP.EMPNO, EMP.ENAME, EMP.JOB, EMP.MGR, EMP.HIREDATE, EMP.SAL, EMP.COMM, EMP.DEPTNO FROM EMP;

-- 3. 원하는 인덱스만 출력
SELECT EMPNO, ENAME FROM EMP;

-- 4. 검색조건 WHERE
SELECT * FROM EMP WHERE EMPNO=7844;
SELECT * FROM EMP WHERE EMPNO!=7844;
SELECT * FROM EMP WHERE DEPNO=30;

-- 5. 조인(join) : 여러 테이블을 연결해서 조회
-- 부서 : emp.deptno = dept.deptno
SELECT EMP.EMPNO, EMP.ENAME, EMP.DEPTNO, DEPT.DEPTNO, DEPT.DNAME, DEPT.LOC
    FROM EMP, DEPT
    WHERE EMP.DEPTNO = DEPT.DEPTNO;

-- 5-1 사원, 부서 테이블에서 소속된 부서명을 추출하고, 부서코드가 30인 사원만 검색
SELECT EMP.EMPNO, EMP.ENAME, EMP.DEPTNO, DEPT.DEPTNO, DEPT.DNAME, DEPT.LOC
    FROM EMP, DEPT
    WHERE EMP.DEPTNO=30
    AND EMP.DEPTNO = DEPT.DEPTNO;


-- 6. 중복제거 : 같은부서 코드는 하나만 출력, DISTINCT 뒤에 오는 모든 칼럼에 대한 중복 체크
-- 사원의 부서코드
SELECT DEPTNO FROM EMP;
SELECT DISTINCT DEPTNO, JOB FROM EMP;
SELECT DISTINCT JOB, DEPTNO FROM EMP ORDER BY JOB, DEPTNO;
-- 사번은 고유하므로 중복제거의 의미가 상실
SELECT DISTINCT JOB, DEPTNO, EMPNO FROM EMP ORDER BY JOB, DEPTNO;


-- 7. SORT 정렬
SELECT * FROM EMP ORDER BY HIREDATE; -- 입사일자 순 정렬
SELECT * FROM EMP ORDER BY 5 DESC; -- 칼럼 위치를 숫자로 지정

-- 7-1. sort ASC(오름차순) : order by 컬럼명 ASC (기본으로 오름차순임)
SELECT JOB, DEPTNO FROM EMP ORDER BY JOB, DEPTNO;
-- 7-2 sort DESC(내림차순) : order by 컬럼명 DESC
SELECT JOB, DEPTNO FROM EMP ORDER BY JOB DESC, DEPTNO;

SELECT * FROM EMP;

-- [문제1]
-- SAL : 월급여, COMM : 월수당
-- 정렬 : 급여, 입사일자
-- 출력 : 이름, 직책, 급여, 입사일자
SELECT ENAME, JOB, SAL, HIREDATE FROM EMP ORDER BY SAL, HIREDATE;


-- [문제2]
-- 정렬 : 총 월급여(급여, 수당), 입사일자
-- 출력 : 이름, 직책, 급여, 수당, 입사일자
SELECT ENAME, JOB, SAL, NVL(COMM,0) AS COMM, HIREDATE, SAL+NVL(COMM,0) AS TOTAL FROM EMP ORDER BY SAL+COMM, HIREDATE;


-- [문제3]
-- 사원의 연간 총 소득
SELECT  ENAME, JOB, SAL, HIREDATE, SAL*12 AS YEARSAL FROM EMP ORDER BY YEARSAL, HIREDATE;
-- 사원의 연간 총 급여
SELECT  ENAME, JOB, SAL, HIREDATE, SAL+NVL(COMM,0)*12 AS YEARCOMM FROM EMP ORDER BY YEARCOMM, HIREDATE;
-- 사원의 월 평균 수입
SELECT  ENAME, JOB, SAL, HIREDATE, (SAL*12+NVL(COMM,0))/12 AS AVGSAL FROM EMP ORDER BY AVGSAL, HIREDATE;


