-- 그룹함수 : 다중행 함수
-- COUNT, AGV, MIN, MAX, SUM
-- GROUP BY, HAVING, GROUP BY ROLLUP, GROUP BY CUBE

--------------------------------------------
-- GROUP BY : 그룹함수를 통해서 나온 결과를 묶어서 처리

-- 부서별 사원들의 평균 급여액
SELECT * FROM DEPT;
SELECT AVG(SAL) FROM EMP WHERE DEPTNO = 10;
SELECT AVG(SAL) FROM EMP WHERE DEPTNO = 20;
SELECT AVG(SAL) FROM EMP WHERE DEPTNO = 30;
SELECT AVG(SAL) FROM EMP WHERE DEPTNO = 40;

-- 집합연산자(합집합)
SELECT '10' AS DEPTNO, TRUNC(AVG(SAL)) FROM EMP WHERE DEPTNO = 10
UNION ALL
SELECT '20' AS DEPTNO, TRUNC(AVG(SAL)) FROM EMP WHERE DEPTNO = 20
UNION ALL
SELECT '30' AS DEPTNO, TRUNC(AVG(SAL)) FROM EMP WHERE DEPTNO = 30
UNION ALL
SELECT '40' AS DEPTNO, TRUNC(AVG(SAL)) FROM EMP WHERE DEPTNO = 40;

-- GROUP BY
-- 그룹화할 컬럼을 지정, 여러 컬럼을 지정 가능
-- 부서별 평균 급여액
SELECT deptno AS 부서, TRUNC(AVG(sal)) AS 평균급여액
    FROM emp 
    GROUP BY deptno;

-- 부서별, 직책별 평균 급여액
SELECT DEPTNO, JOB, SAL FROM EMP;
SELECT DEPTNO, TRUNC(AVG(SAL)) FROM EMP GROUP BY DEPTNO;

-- 부서별 총 급여액
SELECT DEPTNO, SUM(SAL) FROM EMP GROUP BY DEPTNO; -- 얘는 단일행이여서 GROUP BY 사용못함

-- 부서별, 직책별 총 급여액
SELECT DEPTNO, JOB, SUM(SAL) FROM EMP GROUP BY DEPTNO; -- 얘는 단일행이여서 GROUP BY 사용못함

-- [문제]
-- 부서별 사원들의 총 수
SELECT * FROM EMP;
SELECT * FROM DEPT;
SELECT  DEPTNO, COUNT(DEPTNO)FROM EMP GROUP BY DEPTNO;

-- 부서별 사원들의 총수, 급여총액, 평균급여액
SELECT  DEPTNO, COUNT(DEPTNO), SUM(SAL), AVG(SAL) FROM EMP GROUP BY DEPTNO;

-- 부서별 사원들의 급여총액, 평균급여액, 최고급여액, 최저급여액
SELECT  E.DEPTNO,D.DNAME, COUNT(E.EMPNO) AS 사원수, SUM(E.SAL) AS 급여총액, TRUNC(AVG(E.SAL),1) AS 평균급여액, 
                MIN(E.SAL) AS 최저급여액, MAX(E.SAL) AS 최고급여액
    FROM EMP E, DEPT D
    GROUP BY E.DEPTNO
    HAVING COUNT(E.EMPNO)<=3 AND E.DEPTNO = D.DEPTNO
    ORDER BY E.DEPTNO;
    
 -- 부서별 사원들의 급여총액, 평균급여액, 최고급여액, 최저급여액
SELECT deptno, avg(sal), max(sal), min(sal) FROM emp GROUP BY deptno ORDER BY deptno;