-- 서브쿼리를 이용한 입력
-- 서브쿼리를 이용하여 INSERT 를 하는 경우는 VALUES 구문을 생략
-- 조건 : 
    -- 1. 컬럼의 개수가 일치
    -- 2. 컬럼의 자료형이 일치

-- 전체 사원의 급여등급
SELECT * FROM EMP E, SALGRADE S
    WHERE E.SAL BETWEEN S.LOSAL AND S.HISAL;
    
-- 전체 사원중 급여등급이 4등급인 사원
SELECT * FROM EMP E, SALGRADE S
    WHERE E.SAL BETWEEN S.LOSAL AND S.HISAL
    AND S.GRADE = 4;
    
    DROP TABLE EMP4;
-- 전체 사원중 급여등급이 4등급인 사원 테이블
CREATE TABLE EMP4 AS SELECT * FROM EMP WHERE 1 <> 1;

INSERT INTO EMP4
    SELECT E.*
    FROM EMP E, SALGRADE S
    WHERE E.SAL BETWEEN S.LOSAL AND S.HISAL
    AND S.GRADE = 4;


-- 전체 사원중 급여등급이 2등급인 사원 테이블에 입력
-- 제외 컬럼  COMM, DEPTNO
INSERT INTO EMP4 (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL,DEPTNO)
    SELECT E.EMPNO, E.ENAME, E.JOB, E.MGR, SYSDATE, E.SAL, NULL
    FROM EMP E, SALGRADE S
    WHERE E.SAL BETWEEN S.LOSAL AND S.HISAL
    AND S.GRADE = 2;
    
SELECT * FROM EMP4;