desc tab;

select * from tab;
select * from tab where tname = upper('hello');
desc hello;

CREATE TABLE HELLO
(
    ID CHAR(5) CONSTRAINT PK_HELLO_ID PRIMARY KEY,
    NAME VARCHAR2(20),
    TEL VARCHAR2(20),
    AGE NUMBER(3)
);

CREATE TABLE "MIMMI"."HELLO" 
   (	
    "ID" CHAR(5 BYTE), 
    "NAME" VARCHAR2(20 BYTE), 
    "TEL" VARCHAR2(20 BYTE), 
    "AGE" NUMBER(3,0), 
    CONSTRAINT "PK_HELLO_ID" PRIMARY KEY ("ID")
    );
    
CREATE TABLE "HELLO2" 
   (	
    "ID" CHAR(5 BYTE), 
    "HNO" NUMBER(4),
    "NAME" VARCHAR2(20 BYTE), 
    "TEL" VARCHAR2(20 BYTE), 
    "AGE" NUMBER(3,0), 
    CONSTRAINT "PK_HELLO2_ID" PRIMARY KEY ("ID","HNO")
    );
    
INSERT INTO HELLO2 VALUES('10000', 1000,'선도자', NULL, NULL);
INSERT INTO HELLO2 VALUES('10000', 1000,'선도자', NULL, NULL);
INSERT INTO HELLO2 VALUES('10000', 1000,'선도자', NULL, NULL);
-- 오류 유일키 제약조건에 위배됨

--CREATE UNIQUE INDEX "MIMMI"."PK_HELLO2"
    
CREATE TABLE "HELLO3" 
   (	
    "ID" CHAR(5 BYTE), 
    "HNO" NUMBER(4),
    "NAME" VARCHAR2(20 BYTE), 
    "TEL" VARCHAR2(20 BYTE), 
    "AGE" NUMBER(3,0)
    );   
    
INSERT INTO HELLO3 VALUES('10000', 1000,'선도자', NULL, NULL);
INSERT INTO HELLO3 VALUES('10000', 1000,'선도자', NULL, NULL);
INSERT INTO HELLO3 VALUES('10000', 1000,'선도자', NULL, NULL);

SELECT * FROM HELLO3;
CREATE UNIQUE INDEX PK_HELLO3_IDHNO ON HELLO3(ID, HNO);
-- 중복 키가 있습니다. 유일한 인덱스를 작성할 수 없습니다

-- DELETE FROM "MIMMI"."HELLO3" WHERE ROWID = 'AAATI9AAAAAAAM/AAB' AND ORA_ROWSCN = '6382883' and ( "ID" is null or "ID" is not null )

SELECT ROWID, ID, HNO, NAME FROM HELLO3;
INSERT INTO HELLO3 VALUES('10000', 1000,'추종자', NULL, NULL);

DELETE FROM HELLO3 WHERE ROWID='AAATI9AAAAAAAM/AAD';

CREATE TABLE HELLOX AS SELECT * FROM HELLO;
SELECT * FROM HELLOX;

INSERT INTO HELLOX VALUES ('10000', '추종자', NULL, NULL);
CREATE INDEX PK_HELLOX_ID ON HELLOX(ID);
CREATE INDEX PK_HELLOX_NAME ON HELLOX(NAME);

--DELETE 와 다른 점
-- 돌이킬 수없움 롤백못함
TRUNCATE TABLE HELLOX; -- Table HELLOX이(가) 잘렸습니다.
DESC HELLOX;

-- 테이블 삭제
DROP TABLE HELLOX;
-- 테이블 날려벼려서, 기본키 날라감

--  유저 인덱스
SELECT * FROM USER_INDEXES;

-- 특정한 유저 인덱스의 컬럼 정보
SELECT * FROM USER_IND_COLUMNS;
desc USER_IND_COLUMNS;
SELECT A.INDEX_NAME, A.TABLE_NAME, B.COLUMN_POSITION, B.COLUMN_NAME
    FROM USER_INDEXES A, USER_IND_COLUMNS B
    WHERE A.INDEX_NAME = B.INDEX_NAME;

-- 인덱스 삭제
DROP INDEX PK_HELLO3_IDHNO;
    -- 인덱스 삭제는 롤백이 안됨 (당연한거아님?ㅋㅎ)
--ROLLBACK;

-- 테이블 이름 변경
RENAME HELLO3 TO HELLOX;
RENAME PK_HELLO2_IDHNO TO PK_HELLO3_IDHNO;
-- 인덱스 이름은 변경 불가

SELECT * FROM ALL_TABLES WHERE OWNER IN ('MIMMI');

CREATE TABLE HELLO3 AS SELECT * FROM HELLO;


