CREATE TABLE STUDENT
(
    STUDENTID   CHAR(5),
    NAME        VARCHAR2(20),
    CLASS       VARCHAR2(20),
    TEL         VARCHAR2(20),
    POSTNUM     NUMBER(5),
    ADDRESS     VARCHAR2(40),
    CONSTRAINT "PK_STUDENT_ID" PRIMARY KEY (STUDENTID)
); 
