select *from student;

ALTER TABLE STUDENT ADD PROFESSOR VARCHAR2(10);
DESC STUDENT;


ALTER TABLE STUDENT MODIFY PROFESSOR VARCHAR2(20);
DESC STUDENT;

-- STUDENT 테이블에 새 학생 정보 추가
INSERT INTO STUDENT VALUES(1201, '가민지', '2021-0005',NULL);
SELECT * FROM STUDENT;
-- 4번 학생정보 수정한 부분부터 취소 처리하기 위한 COMMIT
COMMIT;
-- 한 학생을 선택하여 데이터를 수정
UPDATE STUDENT SET SNAME ='주식왕' WHERE SNO=50000; 
SELECT * FROM STUDENT;
-- 한 학생을 선택하여 데이터 삭제
DELETE FROM STUDENT WHERE SNO=10000;
SELECT * FROM STUDENT;
-- 수정한 부분부터 취소 처리
ROLLBACK;
SELECT * FROM STUDENT;
