SELECT * FROM EMP
    WHERE DEPTNO IN (SELECT DEPTNO FROM EMP GROUP BY DEPTNO)
    AND SAL IN (SELECT MAX(SAL) FROM EMP GROUP BY DEPTNO);

SELECT * FROM SALGRADE;

SELECT E.EMPNO, E.ENAME, E.SAL, S.GRADE
    FROM EMP E, SALGRADE S
    WHERE E.SAL NOT BETWEEN S.LOSAL AND S.HISAL;

-- 급여등급 범위에 있는 사원들
SELECT E.* FROM EMPX1 E, SALGRADE S
    WHERE E.SAL BETWEEN S.LOSAL AND S.HISAL;
    
-- 급여등급 범위 밖에 있는 사원들
SELECT * FROM EMP
    WHERE EMPNO NOT IN(
        SELECT E.EMPNO
        FROM EMP E, SALGRADE S
        WHERE E.SAL BETWEEN S.LOSAL AND S.HISAL);
        
SELECT * 
    FROM EMP, DEPT 
    WHERE EMP.DEPTNO = DEPT.DEPTNO;
    
SELECT * FROM EMP;
SELECT * FROM DEPT;

SELECT  DEPTNO, COUNT(EMPNO) AS 사원수, SUM(SAL) AS 급여총액, TRUNC(AVG(E.SAL),1) AS 평균급여액,  
                MIN(SAL) AS 최저급여액, MAX(SAL) AS 최고급여액
    FROM EMP
    GROUP BY DEPTNO
    HAVING COUNT(EMPNO)<=3
    ORDER BY DEPTNO DESC;

    
SELECT  E.DEPTNO, COUNT(E.EMPNO) AS 사원수, SUM(E.SAL) AS 급여총액, TRUNC(AVG(E.SAL),1) AS 평균급여액,  
                MIN(E.SAL) AS 최저급여액, MAX(E.SAL) AS 최고급여액, D.DNAME
    FROM EMP E, DEPT D
    GROUP BY D.DEPTNO
    HAVING COUNT(E.EMPNO)<=3
    ORDER BY E.DEPTNO DESC;
    
    
    

SELECT DEPTNO, COUNT(EMPNO) AS 사원수, SUM(SAL) AS 급여총액, TRUNC(AVG(E.SAL),1) AS 평균급여액,  
                MIN(SAL) AS 최저급여액, MAX(SAL) AS 최고급여액
    FROM (SELECT *
        FROM EMP E INNER JOIN DEPT D
        ON E.DEPTNO = D.DEPTNO)
    GROUP BY DEPTNO
    HAVING COUNT(EMPNO)<=3
    ORDER BY DEPTNO DESC;

SELECT *
FROM EMP E INNER JOIN DEPT D
ON E.DEPTNO = D.DEPTNO;


SELECT  E.DEPTNO, COUNT(E.EMPNO) AS 사원수, SUM(E.SAL) AS 급여총액, TRUNC(AVG(E.SAL),1) AS 평균급여액,  
                MIN(E.SAL) AS 최저급여액, MAX(E.SAL) AS 최고급여액, D.DNAME
    FROM EMP E
    INNER
    JOIN DEPT D
    ON E.DEPTNO = D.DEPTNO
    GROUP BY E.DEPTNO;
    
    HAVING COUNT(E.EMPNO)<=3;
    

SELECT  E.DEPTNO, COUNT(E.EMPNO) AS 사원수, SUM(E.SAL) AS 급여총액, TRUNC(AVG(E.SAL),1) AS 평균급여액,  
                MIN(E.SAL) AS 최저급여액, MAX(E.SAL) AS 최고급여액
    FROM EMP E
    INNER
    JOIN DEPT D
    ON E.DEPTNO = D.DEPTNO
    GROUP BY E.DEPTNO
    HAVING COUNT(E.EMPNO)<=3;
      
SELECT *
    FROM EMP E
    LEFT 
    JOIN DEPT D
    ON E.DEPTNO = D.DEPTNO; 
    

SELECT COUNT(K.EMPNO) AS 사원수
FROM (SELECT *
    FROM EMP E
    LEFT 
    JOIN DEPT D
    ON E.DEPTNO = D.DEPTNO) K
GROUP BY K.DEPTNO
HAVING COUNT (K.EMPNO) <= 3;

SELECT *
FROM (SELECT *
    FROM EMP E
    LEFT 
    JOIN DEPT D
    ON E.DEPTNO = D.DEPTNO) K;
    
    
SELECT  E.DEPTNO, COUNT(E.EMPNO) AS 사원수, SUM(E.SAL) AS 급여총액, TRUNC(AVG(E.SAL),1) AS 평균급여액,  
                MIN(E.SAL) AS 최저급여액, MAX(E.SAL) AS 최고급여액
    FROM EMP E, DEPT D
    WHERE E.DEPTNO = D.DEPTNO
    GROUP BY E.DEPTNO
    HAVING COUNT(E.EMPNO)<=3;
    
    
SELECT K.DEPTNO, K.사원수, K.급여총액, K.평균급여액, K.최저급여액, K.최고급여액, D.DNAME AS 부서명
FROM (SELECT  E.DEPTNO, COUNT(E.EMPNO) AS 사원수, SUM(E.SAL) AS 급여총액, TRUNC(AVG(E.SAL),1) AS 평균급여액,  
                MIN(E.SAL) AS 최저급여액, MAX(E.SAL) AS 최고급여액
    FROM EMP E INNER JOIN DEPT D
    ON E.DEPTNO = D.DEPTNO
    GROUP BY E.DEPTNO
    HAVING COUNT(E.EMPNO)<=3) K, DEPT D
WHERE K.DEPTNO = D.DEPTNO
ORDER BY K.DEPTNO DESC;

