-- NOT IN
SELECT EMPNO, ENAME, SAL, JOB, MGR
    FROM EMP
    WHERE EMPNO NOT IN (SELECT MGR
                            FROM EMP
                            WHERE MGR IS NOT NULL);
                            
SELECT DISTINCT MGR FROM EMP;

-- EXISTS
SELECT * FROM DEPT D
    WHERE EXISTS (SELECT * FROM EMP E WHERE E.DEPTNO = D.DEPTNO);
    
-- NOT EXISTS
SELECT * FROM DEPT D
    WHERE NOT EXISTS (SELECT * FROM EMP E WHERE E.DEPTNO = D.DEPTNO);
    
-- HAVING
SELECT JOB, SUM(SAL)
    FROM EMP
    GROUP BY JOB
    HAVING SUM(SAL)> (SELECT SUM(SAL)
                            FROM EMP
                            WHERE JOB='SALESMAN');

SELECT JOB, SUM(SAL)
    FROM EMP
    GROUP BY JOB;

-- FROM
SELECT V.ENAME, V.SAL, V.순위
    FROM (SELECT ENAME, SAL, RANK() OVER (ORDER BY SAL DESC) 순위
            FROM EMP)V
    WHERE V.순위=1;
    
SELECT ENAME, SAL, RANK() OVER (ORDER BY SAL DESC) AS 순위
            FROM EMP;
            
-- SELECT
SELECT ENAME, SAL, (SELECT MAX(SAL) FROM EMP WHERE JOB='SALESMAN')AS 최대월급,
                    (SELECT MIN(SAL) FROM EMP WHERE JOB='SALESMAN')AS 최소월급
FROM EMP
WHERE JOB='SALESMAN';