CREATE TABLE HELLO
(
    ID CHAR(5) CONSTRAINT PK_HELLO_ID PRIMARY KEY,
    NAME VARCHAR2(20),
    TEL VARCHAR2 (20),
    AGE NUMBER(3)
);
    
INSERT INTO "MIMMI"."HELLO" (ID, NAME, TEL, AGE) VALUES ('12345', 'ȫ�浿', 010-1234-1234,30);

DROP TABLE HELLO;

CREATE TABLE PHONEBOOK
(
    ID       CHAR(10) CONSTRAINT PHONEBOOK_ID_PK PRIMARY KEY,
    NAME     VARCHAR2(20),
    CELLTEL  VARCHAR2(20) CONSTRAINT PHONEBOOK_CELLTEL_UN UNIQUE,
    PHONETEL VARCHAR2(20),
    POSTALADDRESS VARCHAR2(80),
    DETAILADDRESS VARCHAR2(80),
    POSTCD NUMBER(6),
    EMAIL VARCHAR2(80),
    GROUPID VARCHAR2(20),
    MEMO VARCHAR2(80)
);

CREATE TABLE PHONEGROUP
(   GROUPID CHAR(10) CONSTRAINT PGROUP_PHONEGROUP_PK PRIMARY KEY,
    GROUPNAME VARCHAR2(20),
    GROUPINFO VARCHAR2 (80),
    GROUPTYPE VARCHAR2(20)
    --CONSTRAINT PHONEGROUP_GROUPID_FK REFERENCES PHONEBOOK(GROUPID)
);

CREATE TABLE POSTINFO
(
    POSTCD NUMBER(6),
    LOTADDRESS VARCHAR2(80),
    STREETADDRESS VARCHAR2(80)
    --CONSTRAINT POSTINFO_POSTCD_FK REFERENCES PHONEBOOK(POSTCD)
);

DROP TABLE PHONEBOOK;
DROP TABLE PGROUP;